### ISSUE TITLE
Authorizing discogs lets crash vinylscrobbler

### ISSUE THREAD

**Issue by MartinL0815** [tjol/vinylscrobbler#14]
Hi,

due to the bug "Cannot comprehend data" I thought about re-authorizing discogs.

I shouldn't have tried this, because now I can't authorize again!
After opening the browser window vinylscrobbler crashes.

Sincerely the crash feedback doesn't seem to allow to view the call stack, so I help with some more information!
But I send the crash feedback with my google account <forname><lastname><town>DE at gmail.com.

**Comment by tjol** [comment]
Thanks for the bug reports Martin. A fixed version has been uploaded to Google Play and should reach you within a few hours. Sorry for the late response.

**Comment by MartinL0815** [comment]
Thanks @tjol for fixing this error such quickly!

Yes - you are right about owing nothing to me!
And ... yes you are right, that this "old" and barely updated application may have some issues to be fixed.

But on the other hand having such a rare application to scrobble this way to last.fm, such announcements from discogs could lead to fixes just before application users may stumble upon.
That's all.

Cheers and a good Sunday!
